import { DEFAULT_ACTIVATION_CONFIG, DEFAULT_THRESHOLDS } from './constants.js';

export function createMonthId(prefix = 'm') {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

export function createEmptyMonth(month) {
  const now = new Date().toISOString();
  return {
    id: createMonthId(),
    createdAt: now,
    updatedAt: now,
    month,
    customersAtStart: 0,
    newSignedCustomers: 0,
    newPayingCustomers: 0,
    activatedCustomers: 0,
    churnedCustomers: 0,
    reactivatedCustomers: 0,
    activePayingCustomersEnd: 0,
    startingMRR: 0,
    newMRR: 0,
    expansionMRR: 0,
    contractionMRR: 0,
    churnedMRR: 0,
    reactivationMRR: 0,
    recurringRevenueRecognized: 0,
    subscriptionCashIn: 0,
    oneTimeServicesRevenue: 0,
    discountsCreditsRefunds: 0,
    totalRecognizedRevenue: 0,
    totalCashIn: 0,
    averageBaseFee: 0,
    modulesRevenue: 0,
    usageBasedRevenue: 0,
    activeCabinets: 0,
    activeSKUs: 0,
    managedGMV: 0,
    activeUsersOrSeats: 0,
    marketingCost: 0,
    salesCost: 0,
    partnerAcquisitionCost: 0,
    onboardingCost: 0,
    supportCost: 0,
    csmCost: 0,
    analystServiceCost: 0,
    infraCloudCost: 0,
    apiAiCost: 0,
    partnerCommissions: 0,
    timeToValueDays: 0,
    featureUsageCount: 0,
    connectedCabinetsCount: 0,
    activeDaysForActivation: 0,
    activationThresholdPassed: false,
    notes: '',
  };
}

export function createDefaultAppState() {
  return {
    selectedMonthId: null,
    thresholds: structuredClone(DEFAULT_THRESHOLDS),
    activationConfig: structuredClone(DEFAULT_ACTIVATION_CONFIG),
  };
}

export function createSeedMonths() {
  const now = new Date().toISOString();
  const createSeedId = () => `m_seed_${Math.random().toString(36).slice(2, 8)}`;
  return [
    {
      month: '2025-09',
      customersAtStart: 45,
      newSignedCustomers: 8,
      newPayingCustomers: 6,
      activatedCustomers: 5,
      churnedCustomers: 1,
      reactivatedCustomers: 0,
      activePayingCustomersEnd: 50,
      startingMRR: 3_200_000,
      newMRR: 480_000,
      expansionMRR: 120_000,
      contractionMRR: 30_000,
      churnedMRR: 65_000,
      reactivationMRR: 0,
      recurringRevenueRecognized: 3_705_000,
      subscriptionCashIn: 4_100_000,
      oneTimeServicesRevenue: 380_000,
      discountsCreditsRefunds: 50_000,
      totalRecognizedRevenue: 4_035_000,
      totalCashIn: 4_500_000,
      averageBaseFee: 74_100,
      modulesRevenue: 0,
      usageBasedRevenue: 0,
      activeCabinets: 142,
      activeSKUs: 28_500,
      managedGMV: 84_000_000,
      activeUsersOrSeats: 68,
      marketingCost: 420_000,
      salesCost: 680_000,
      partnerAcquisitionCost: 85_000,
      onboardingCost: 90_000,
      supportCost: 180_000,
      csmCost: 220_000,
      analystServiceCost: 110_000,
      infraCloudCost: 280_000,
      apiAiCost: 190_000,
      partnerCommissions: 55_000,
      timeToValueDays: 12,
      featureUsageCount: 8,
      connectedCabinetsCount: 3,
      activeDaysForActivation: 9,
      activationThresholdPassed: true,
      notes: 'Сентябрь — запуск новой когорты WB-партнёров',
    },
    {
      month: '2025-10',
      customersAtStart: 50,
      newSignedCustomers: 10,
      newPayingCustomers: 8,
      activatedCustomers: 7,
      churnedCustomers: 2,
      reactivatedCustomers: 1,
      activePayingCustomersEnd: 57,
      startingMRR: 3_705_000,
      newMRR: 620_000,
      expansionMRR: 185_000,
      contractionMRR: 42_000,
      churnedMRR: 95_000,
      reactivationMRR: 60_000,
      recurringRevenueRecognized: 4_433_000,
      subscriptionCashIn: 4_800_000,
      oneTimeServicesRevenue: 520_000,
      discountsCreditsRefunds: 65_000,
      totalRecognizedRevenue: 4_888_000,
      totalCashIn: 5_200_000,
      averageBaseFee: 77_770,
      modulesRevenue: 0,
      usageBasedRevenue: 0,
      activeCabinets: 168,
      activeSKUs: 33_200,
      managedGMV: 102_000_000,
      activeUsersOrSeats: 78,
      marketingCost: 490_000,
      salesCost: 760_000,
      partnerAcquisitionCost: 95_000,
      onboardingCost: 110_000,
      supportCost: 195_000,
      csmCost: 240_000,
      analystServiceCost: 130_000,
      infraCloudCost: 310_000,
      apiAiCost: 215_000,
      partnerCommissions: 68_000,
      timeToValueDays: 10,
      featureUsageCount: 10,
      connectedCabinetsCount: 3,
      activeDaysForActivation: 8,
      activationThresholdPassed: true,
      notes: 'Октябрь — рост GMV, первые Ozon клиенты',
    },
    {
      month: '2025-11',
      customersAtStart: 57,
      newSignedCustomers: 12,
      newPayingCustomers: 9,
      activatedCustomers: 8,
      churnedCustomers: 2,
      reactivatedCustomers: 1,
      activePayingCustomersEnd: 65,
      startingMRR: 4_433_000,
      newMRR: 710_000,
      expansionMRR: 260_000,
      contractionMRR: 58_000,
      churnedMRR: 110_000,
      reactivationMRR: 85_000,
      recurringRevenueRecognized: 5_320_000,
      subscriptionCashIn: 5_690_000,
      oneTimeServicesRevenue: 590_000,
      discountsCreditsRefunds: 75_000,
      totalRecognizedRevenue: 5_835_000,
      totalCashIn: 6_200_000,
      averageBaseFee: 81_850,
      modulesRevenue: 0,
      usageBasedRevenue: 0,
      activeCabinets: 192,
      activeSKUs: 40_800,
      managedGMV: 128_000_000,
      activeUsersOrSeats: 91,
      marketingCost: 560_000,
      salesCost: 830_000,
      partnerAcquisitionCost: 102_000,
      onboardingCost: 128_000,
      supportCost: 212_000,
      csmCost: 255_000,
      analystServiceCost: 138_000,
      infraCloudCost: 352_000,
      apiAiCost: 240_000,
      partnerCommissions: 76_000,
      timeToValueDays: 9,
      featureUsageCount: 12,
      connectedCabinetsCount: 4,
      activeDaysForActivation: 7,
      activationThresholdPassed: true,
      notes: 'Ноябрь — предсезонный рост и подготовка крупных кабинетов',
    },
  ].map((item) => ({ ...item, id: createSeedId(), createdAt: now, updatedAt: now }));
}
