export const FIELD_GROUPS = [
  {
    id: 'customers',
    title: 'Клиентская база и активация',
    hint: 'Фундамент для logo churn, activation rate и CAC.',
    fields: [
      ['month', 'Месяц', 'month'],
      ['customersAtStart', 'Клиентов на начало'],
      ['newSignedCustomers', 'Новых подписанных'],
      ['newPayingCustomers', 'Новых платящих', 'number', 'Из подписанных дошли до оплаты.'],
      ['activatedCustomers', 'Активированных', 'number', 'Дошли до activation threshold.'],
      ['churnedCustomers', 'Ушедших клиентов'],
      ['reactivatedCustomers', 'Реактивированных клиентов'],
      ['activePayingCustomersEnd', 'Активных плательщиков на конец', 'number', 'Можно оставить 0, тогда значение будет рассчитано автоматически.'],
      ['timeToValueDays', 'Time to Value, дней'],
      ['featureUsageCount', 'Использование ключевой функции'],
      ['connectedCabinetsCount', 'Подключённых кабинетов'],
      ['activeDaysForActivation', 'Активных дней для активации'],
    ],
  },
  {
    id: 'revenue',
    title: 'MRR и выручка',
    hint: 'Основные входы для NRR, GRR, Quick Ratio и Rule of 40.',
    fields: [
      ['startingMRR', 'Starting MRR, ₽'],
      ['newMRR', 'New MRR, ₽'],
      ['expansionMRR', 'Expansion MRR, ₽'],
      ['contractionMRR', 'Contraction MRR, ₽'],
      ['churnedMRR', 'Churned MRR, ₽'],
      ['reactivationMRR', 'Reactivation MRR, ₽'],
      ['recurringRevenueRecognized', 'Recognized recurring revenue, ₽', 'number', 'Если 0, будет использован Ending MRR.'],
      ['subscriptionCashIn', 'Cash-in по подписке, ₽'],
      ['oneTimeServicesRevenue', 'One-time services revenue, ₽'],
      ['modulesRevenue', 'Модульная выручка, ₽'],
      ['usageBasedRevenue', 'Usage-based выручка, ₽'],
      ['discountsCreditsRefunds', 'Скидки / кредиты / рефанды, ₽'],
      ['totalRecognizedRevenue', 'Total recognized revenue, ₽', 'number', 'Необязательное поле. Можно оставить 0 и считать автоматически.'],
      ['totalCashIn', 'Total cash-in, ₽', 'number', 'Необязательное поле. Можно оставить 0 и считать автоматически.'],
      ['averageBaseFee', 'Средний базовый тариф, ₽'],
    ],
  },
  {
    id: 'scale',
    title: 'Масштаб продукта',
    hint: 'Поля помогают интерпретировать unit-экономику и sanity-check данных.',
    fields: [
      ['activeCabinets', 'Активных кабинетов'],
      ['activeSKUs', 'Активных SKU'],
      ['managedGMV', 'Управляемый GMV, ₽'],
      ['activeUsersOrSeats', 'Активных пользователей / seats'],
    ],
  },
  {
    id: 'costs',
    title: 'Привлечение и cost stack',
    hint: 'Расходы разделены по слоям: acquisition, delivery, support.',
    fields: [
      ['marketingCost', 'Маркетинг, ₽'],
      ['salesCost', 'Продажи, ₽'],
      ['partnerAcquisitionCost', 'Привлечение партнёров, ₽'],
      ['onboardingCost', 'Онбординг, ₽'],
      ['supportCost', 'Поддержка, ₽'],
      ['csmCost', 'CSM, ₽'],
      ['analystServiceCost', 'Аналитика / сервис, ₽'],
      ['infraCloudCost', 'Инфра / cloud, ₽'],
      ['apiAiCost', 'API / AI, ₽'],
      ['partnerCommissions', 'Комиссии партнёров, ₽'],
    ],
  },
  {
    id: 'meta',
    title: 'Заметки и служебные поля',
    hint: 'Полезно для shared snapshot и чтения истории расчёта.',
    fields: [
      ['activationThresholdPassed', 'Порог активации достигнут', 'checkbox'],
      ['notes', 'Комментарий', 'textarea'],
    ],
  },
];
