export const FIELD_GROUPS = [
  {
    id: 'customers',
    title: 'Клиентская база и активация',
    hint: 'Основа для logo churn, activation rate и CAC.',
    fields: [
      ['month', 'Месяц', 'month'],
      ['customersAtStart', 'Клиентов на начало'],
      ['newSignedCustomers', 'Новых подписанных'],
      ['newPayingCustomers', 'Новых платящих', 'number', 'Из подписанных дошли до оплаты.'],
      ['activatedCustomers', 'Активированных', 'number', 'Дошли до порога активации.'],
      ['churnedCustomers', 'Ушедших клиентов'],
      ['reactivatedCustomers', 'Реактивированных клиентов'],
      ['activePayingCustomersEnd', 'Активных плательщиков на конец', 'number', 'Оставьте 0 — значение рассчитается автоматически.'],
      ['timeToValueDays', 'Time to Value, дней'],
      ['featureUsageCount', 'Использование ключевой функции'],
      ['connectedCabinetsCount', 'Подключённых кабинетов'],
      ['activeDaysForActivation', 'Активных дней для активации'],
    ],
  },
  {
    id: 'revenue',
    title: 'MRR и выручка',
    hint: 'Ключевые входы для NRR, GRR, Quick Ratio и Rule of 40.',
    fields: [
      ['startingMRR', 'Starting MRR, ₽'],
      ['newMRR', 'New MRR, ₽'],
      ['expansionMRR', 'Expansion MRR, ₽'],
      ['contractionMRR', 'Contraction MRR, ₽'],
      ['churnedMRR', 'Churned MRR, ₽'],
      ['reactivationMRR', 'Reactivation MRR, ₽'],
      ['recurringRevenueRecognized', 'Recognized recurring revenue, ₽', 'number', 'Если 0, будет использован Ending MRR.'],
      ['subscriptionCashIn', 'Cash-in по подписке, ₽'],
      ['oneTimeServicesRevenue', 'One-time services revenue, ₽'],
      ['modulesRevenue', 'Модульная выручка, ₽'],
      ['usageBasedRevenue', 'Usage-based выручка, ₽'],
      ['discountsCreditsRefunds', 'Скидки / кредиты / рефанды, ₽'],
      ['totalRecognizedRevenue', 'Total recognized revenue, ₽', 'number', 'Необязательно. Оставьте 0 для автоматического расчёта.'],
      ['totalCashIn', 'Total cash-in, ₽', 'number', 'Необязательно. Оставьте 0 для автоматического расчёта.'],
      ['averageBaseFee', 'Средний базовый тариф, ₽'],
    ],
  },
  {
    id: 'scale',
    title: 'Масштаб продукта',
    hint: 'Помогает интерпретировать unit economics и проверить здравость данных.',
    fields: [
      ['activeCabinets', 'Активных кабинетов'],
      ['activeSKUs', 'Активных SKU'],
      ['managedGMV', 'Управляемый GMV, ₽'],
      ['activeUsersOrSeats', 'Активных пользователей / seats'],
    ],
  },
  {
    id: 'costs',
    title: 'Привлечение и cost stack',
    hint: 'Расходы по слоям: acquisition, delivery, support.',
    fields: [
      ['marketingCost', 'Маркетинг, ₽'],
      ['salesCost', 'Продажи, ₽'],
      ['partnerAcquisitionCost', 'Привлечение партнёров, ₽'],
      ['onboardingCost', 'Онбординг, ₽'],
      ['supportCost', 'Поддержка, ₽'],
      ['csmCost', 'CSM, ₽'],
      ['analystServiceCost', 'Аналитика / сервис, ₽'],
      ['infraCloudCost', 'Инфра / cloud, ₽'],
      ['apiAiCost', 'API / AI, ₽'],
      ['partnerCommissions', 'Комиссии партнёров, ₽'],
    ],
  },
  {
    id: 'meta',
    title: 'Заметки',
    hint: 'Контекст для shared snapshot и истории расчёта.',
    fields: [
      ['activationThresholdPassed', 'Порог активации достигнут', 'checkbox'],
      ['notes', 'Комментарий', 'textarea'],
    ],
  },
];
