export const GLOSSARY = [
  {
    key: 'nrr',
    name: 'NRR',
    formula: '(Starting MRR + Expansion + Reactivation − Contraction − Churn) / Starting MRR × 100%',
    definition: 'Показывает, удерживает ли бизнес выручку внутри существующей клиентской базы.',
    interpretation: 'Для B2B SaaS ориентир — 100%+, сильный результат — 105%+.',
    category: 'retention',
  },
  {
    key: 'grr',
    name: 'GRR',
    formula: '(Starting MRR − Churned MRR − Contraction MRR) / Starting MRR × 100%',
    definition: 'Базовое удержание без учёта expansion и reactivation.',
    interpretation: 'Слабый GRR может маскироваться ростом от expansion.',
    category: 'retention',
  },
  {
    key: 'quickRatio',
    name: 'Quick Ratio',
    formula: '(New MRR + Expansion + Reactivation) / (Churned MRR + Contraction MRR)',
    definition: 'Показывает, насколько рост выручки перекрывает потери.',
    interpretation: '4+ — сильный уровень, 2–4 — умеренно, ниже 2 — тревожный сигнал.',
    category: 'efficiency',
  },
  {
    key: 'ltvCac',
    name: 'LTV:CAC',
    formula: 'LTV / CAC',
    definition: 'Отношение lifetime value к стоимости привлечения клиента.',
    interpretation: '3x — здоровый уровень для B2B SaaS; ниже 1x — привлечение не окупается.',
    assumption: 'LTV считается упрощённо: (ARPA × Gross Margin %) / Logo Churn Rate. Используется logo churn, не revenue churn — для быстрой оценки, не для финансового аудита.',
    category: 'efficiency',
  },
  {
    key: 'payback',
    name: 'CAC Payback',
    formula: 'CAC / contribution margin per customer',
    definition: 'Сколько месяцев нужно, чтобы вернуть инвестиции в привлечение.',
    interpretation: 'До 12 месяцев — хорошо; 12–24 — терпимо; дальше — давление на cash flow.',
    category: 'efficiency',
  },
  {
    key: 'grossMargin',
    name: 'Gross Margin',
    formula: '(Recognized Revenue − COGS) / Recognized Revenue × 100%',
    definition: 'Доля выручки после прямых delivery- и infra-затрат.',
    interpretation: 'Для SaaS обычно ориентир — 70%+.',
    category: 'margin',
  },
  {
    key: 'romi',
    name: 'ROMI',
    formula: '(LTV − CAC) / CAC × 100%',
    definition: 'Маркетинговая эффективность на базе LTV и CAC.',
    interpretation: 'Полезно для сравнения сценариев, но чувствительно к допущениям LTV.',
    assumption: 'В калькуляторе это упрощённый показатель эффективности привлечения, а не классический ROMI по cash-периоду кампании.',
    category: 'efficiency',
  },
  {
    key: 'ruleOf40',
    name: 'Rule of 40',
    formula: 'Revenue growth % + profit margin %',
    definition: 'Баланс роста и прибыльности для зрелого SaaS.',
    interpretation: '40+ — сильный сигнал; 20–40 — допустимо; ниже 20 — нужна корректировка стратегии.',
    category: 'efficiency',
  },
];

export const METHODOLOGY_NOTE = 'Калькулятор предназначен для продуктовых и управленческих решений на российском рынке. Метрики считаются по единым pure-функциям; пороги health score можно менять под свой контекст.';
