export const GLOSSARY = [
  {
    key: 'nrr',
    nameRu: 'Net Revenue Retention',
    nameEn: 'NRR',
    formula: '(Starting MRR + Expansion + Reactivation − Contraction − Churn) / Starting MRR × 100%',
    definition: 'Показывает, удерживает ли бизнес выручку внутри существующей клиентской базы.',
    interpretation: 'Для B2B SaaS обычно хочется видеть 100%+; 105%+ уже выглядит сильным результатом.',
    category: 'retention',
  },
  {
    key: 'grr',
    nameRu: 'Gross Revenue Retention',
    nameEn: 'GRR',
    formula: '(Starting MRR − Churned MRR − Contraction MRR) / Starting MRR × 100%',
    definition: 'Базовое удержание без учёта expansion и reactivation.',
    interpretation: 'Если GRR слабый, expansion может маскировать проблему.',
    category: 'retention',
  },
  {
    key: 'quickRatio',
    nameRu: 'Quick Ratio',
    nameEn: 'SaaS Quick Ratio',
    formula: '(New MRR + Expansion + Reactivation) / (Churned MRR + Contraction MRR)',
    definition: 'Показывает, насколько рост выручки перекрывает потери.',
    interpretation: '4+ считается сильным уровнем, 2–4 — умеренно, ниже 2 — тревожный сигнал.',
    category: 'efficiency',
  },
  {
    key: 'ltvCac',
    nameRu: 'LTV:CAC',
    nameEn: 'LTV:CAC',
    formula: 'LTV / CAC',
    definition: 'Отношение lifetime value к стоимости привлечения клиента.',
    interpretation: '3x — здоровый уровень для B2B SaaS; ниже 1x привлечение не окупается.',
    category: 'efficiency',
  },
  {
    key: 'payback',
    nameRu: 'Payback',
    nameEn: 'CAC Payback',
    formula: 'CAC / contribution margin per customer',
    definition: 'Сколько месяцев нужно, чтобы вернуть инвестиции в привлечение.',
    interpretation: 'До 12 месяцев — хорошо; 12–24 — терпимо; дальше уже опасно для cash flow.',
    category: 'efficiency',
  },
  {
    key: 'grossMargin',
    nameRu: 'Gross Margin',
    nameEn: 'Gross Margin',
    formula: '(Recognized Revenue − COGS) / Recognized Revenue × 100%',
    definition: 'Показывает, какая доля выручки остаётся после прямых delivery- и infra-затрат.',
    interpretation: 'Для SaaS обычно хочется 70%+.',
    category: 'margin',
  },
  {
    key: 'romi',
    nameRu: 'ROMI',
    nameEn: 'Return on Marketing Investment',
    formula: '(LTV − CAC) / CAC × 100%',
    definition: 'Доходность маркетинговых инвестиций на основе LTV и CAC.',
    interpretation: 'Высокий ROMI полезен, но зависит от качества расчёта LTV.',
    category: 'efficiency',
  },
  {
    key: 'ruleOf40',
    nameRu: 'Rule of 40',
    nameEn: 'Rule of 40',
    formula: 'Revenue growth % + profit margin %',
    definition: 'Баланс роста и прибыльности, классический компас зрелой SaaS-компании.',
    interpretation: '40+ — сильный сигнал; 20–40 — допустимо; ниже 20 — нужна корректировка стратегии.',
    category: 'revenue',
  },
];
